### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by ddollar**
Adds a Dockerfile to easily get a fakes3 server up and running.

```
$ docker build -t fakes3 .
...

$ docker run -p 5000:80 fakes3
```

### CODE REVIEW

**Comment by jaredgisin** [comment]
+1

**Comment by omarkhan** [comment]
:+1:

**Comment by bradgessler** [comment]
:+1:

**Comment by jeshuaborges** [comment]
:+1:

**Comment by olalonde** [comment]
Wrote this in the meanwhile: https://github.com/olalonde/docker-fake-s3

Been using it for a few weeks and works pretty well.

**Comment by pickhardt** [comment]
Hi all. The repo now has a Dockerfile, so I'm closing this pull request.

**Pull request closed without merging**
