### PR TITLE
DeleteObjects

### PR DESCRIPTION
**Pull request by pola88**

### CODE REVIEW

**Comment by nwind21** [comment]
I'm interested in this feature. Is there anyone actively reviewing PR's and @pola88 did you plan to fix the conflicts? Kinda bummed that the original PR was submitted in 2014 and never merged nor commented on.

**Comment by pickhardt** [comment]
Hey, I'm going through the old PRs and issues every week, making progress. I'll do this one this weekend.

**Comment by pickhardt** [comment]
Hi @pola88,

Thanks for the pull request!

I can merge it in if you do just three things:

1. Is the rvmrc file necessary? I think it should be removed.

2. Can you rebase against master? I must've made some changes since you made the PR. Apologies for not reviewing this sooner. I took over as lead maintainer recently and am gradually making progress going over the old PRs and issues.

3. We have a contributor license agreement (CLA) based off of Google and Apache's CLA. If you would feel comfortable contributing to, say, Angular.js, you should feel comfortable with this CLA.

Go here to sign the CLA: https://docs.google.com/forms/d/e/1FAIpQLSeKKSKNNz5ji1fd5bbu5RaGFbhD45zEaCnAjzBZPpzOaXQsvQ/viewform

If you're interested, this blog post discusses why to use a CLA, and even goes over the text of the CLA we based ours on.

Thanks a lot, and if you do those I promise I'll get to it sooner than last time!

**Comment by pola88** [comment]
Hi @pickhardt 

No problem,
1) I will remove the `.rvmrc` (it is not necessary) 
2) Ok, I will rebase against master and update the PR.
3) Let me take a look.

Thanks, 
PoLa.

**Comment by jancurn** [comment]
Hey guys, any chance to merge this PR? We really need this feature, so we have no choice but to maintain or own fork of this repo.

**Comment by kelcecil** [comment]
If @pola88 doesn't respond, is someone else welcome to jump in and address the final issues to get this ready to merge?

**Comment by pickhardt** [comment]
Sorry we haven't responded since Jan. Let me look at it again and see if it can be merged.

**Comment by jancurn** [comment]
Amazing, many thanks!

**Comment by jancurn** [comment]
Hey guys, does the released version of fakes3 already contain this merge? Looking at https://rubygems.org/gems/fakes3/versions/ the latest version 1.2.0 was released on May 13, but this PR was only merged in June.

**Pull request merged**
