### PR TITLE
Added enhanced CORS support. Allows signed URL uploads/retrievals to work

### PR DESCRIPTION
**Pull request by iq-dot**
Modified OPTIONS request to emulate the same recommended CORS setup.
Modified PUTS request to enable CORS and allows signed uploads to
succeed.
Modified GET request to allow CORS support for signed get URLs
to work.

### CODE REVIEW

**Comment by MathewT** [comment]
Thanks for this fix!  I tested my own fork of fake-s3 and it works great.

**Comment by jubos** [comment]
I merged this with some style fixes into master.  Thanks again for the feature!

**Comment by MathewT** [comment]
Great.  Thanks!

**Comment by iq-dot** [comment]
Great to see it merged, thanks for merging it in.

**Pull request closed without merging**
